name: predictDDG
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - biopython
  - transformers
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8  # Change to 12.1 or 12.4 depending on your GPU driver